-- Adicionar novas colunas ao plano de parto
ALTER TABLE birth_plans 
ADD COLUMN IF NOT EXISTS doctor_preference TEXT,
ADD COLUMN IF NOT EXISTS lighting TEXT,
ADD COLUMN IF NOT EXISTS music BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS movement BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS pain_relief_natural BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS pain_relief_epidural BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS pain_relief_other TEXT,
ADD COLUMN IF NOT EXISTS labor_position TEXT,
ADD COLUMN IF NOT EXISTS monitoring TEXT,
ADD COLUMN IF NOT EXISTS hydration_food BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS delivery_type TEXT,
ADD COLUMN IF NOT EXISTS episiotomy TEXT,
ADD COLUMN IF NOT EXISTS umbilical_cord TEXT,
ADD COLUMN IF NOT EXISTS skin_to_skin BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS breastfeeding TEXT,
ADD COLUMN IF NOT EXISTS baby_bath TEXT,
ADD COLUMN IF NOT EXISTS companion_presence BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS photos BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS religious_cultural TEXT,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();

